apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      containers:
      - name: portfolio-app-container
        image: python:3.10
        image: cobalten/portfolio:dev-deploy
        command: ['/bin/bash', '/app/run.sh']
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: config.settings
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DJANGO_SECRET_KEY
        - name: DJANGO_EMAIL_HOST
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DJANGO_EMAIL_HOST
        - name: DJANGO_EMAIL_PORT
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DJANGO_EMAIL_PORT
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: EMAIL_HOST_USER
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: EMAIL_HOST_PASSWORD
        - name: DEFAULT_FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DEFAULT_FROM_EMAIL
        - name: DEFAULT_TO_EMAIL
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DEFAULT_TO_EMAIL
