apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: cobalten/portfolio:dev-deploy
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: config.settings
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DJANGO_SECRET_KEY
        - name: DJANGO_EMAIL_HOST
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DJANGO_EMAIL_HOST
        - name: DJANGO_EMAIL_PORT
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DJANGO_EMAIL_PORT
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: EMAIL_HOST_USER
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: EMAIL_HOST_PASSWORD
        - name: DEFAULT_FROM_EMAIL
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DEFAULT_FROM_EMAIL
        - name: DEFAULT_TO_EMAIL
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DEFAULT_TO_EMAIL
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PORT
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
