server {
    listen 80;
    server_name portfolio.cobaemon.container;

    access_log /var/log/nginx/container_nginx_portfolio_http_access.log;
    error_log /var/log/nginx/container_nginx_portfolio_http_error.log;

    location /static/ {
        alias /static/portfolio/;
        expires 30d;  # 30日間のキャッシュ
        access_log off;  # アクセスログを無効化
    }

    location / {
        proxy_pass http://web:8000;  # Djangoアプリケーションが稼働しているポート
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocketのサポートとセキュリティ強化
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # タイムアウト設定
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }
}
