server {
    listen 80;
    server_name portfolio.cobaemon.container;

    access_log /var/log/nginx/container_nginx_portfolio_http_access.log;
    error_log /var/log/nginx/container_nginx_portfolio_http_error.log;

    location /static/ {
        alias /static/portfolio/;
        expires 30d;
        add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    }

    location / {
        proxy_pass http://web:8000;  # Djangoアプリケーションが稼働しているポート
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-CSRFToken $http_x_csrf_token;
        proxy_set_header Cookie $http_cookie;

        # プロキシキャッシュの設定
        proxy_no_cache $http_x_csrf_token;
        proxy_no_cache $cookie_csrftoken;
        proxy_cache_bypass $http_x_csrf_token;
        proxy_cache_bypass $cookie_csrftoken;
        proxy_cache portfolio_cache;
        proxy_cache_valid 200 60m;
        proxy_cache_valid 404 1m;
        proxy_cache_key "$scheme$request_method$host$request_uri";
    }
}
