# ベースイメージ
FROM python:3.10-slim

# 必要なパッケージのインストール
RUN apt-get update && apt-get upgrade -y && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# 作業ディレクトリの設定
WORKDIR /app

# リポジトリのURLを環境変数として設定
ENV REPO_URL=https://github.com/cobaemon/Portfolio.git
ENV REPO_DIR=/app/Portfolio
ENV BRANCH_NAME=dev2-deploy-nginx

# リポジトリのクローンまたは更新
RUN if [ -d "$REPO_DIR/.git" ]; then \
        cd $REPO_DIR && git pull origin $BRANCH_NAME; \
    else \
        git clone -b $BRANCH_NAME $REPO_URL $REPO_DIR; \
    fi
    
# 依存関係のインストール
WORKDIR	/app/Portfolio
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN django-admin compilemessages

# アプリケーションの起動
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "config.wsgi:application", \
     "--access-logfile", "/app/Portfolio/logs/gunicorn_access.log", \
     "--error-logfile", "/app/Portfolio/logs/gunicorn_error.log"]
