server {
    listen 80;
    server_name portfolio.cobaemon.com;

    access_log /var/log/nginx/host_nginx_portfolio_http_access.log;
    error_log /var/log/nginx/host_nginx_portfolio_http_error.log;

    # HTTPからHTTPSへのリダイレクト
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name portfolio.cobaemon.com;

    ssl_certificate /etc/letsencrypt/live/portfolio.cobaemon.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/portfolio.cobaemon.com/privkey.pem;

    access_log /var/log/nginx/host_nginx_portfolio_https_access.log;
    error_log /var/log/nginx/host_nginx_portfolio_https_error.log;

    # その他のセキュリティ関連の設定
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;
    ssl_session_timeout 10m;

    # セキュリティヘッダーの追加
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    # add_header Content-Security-Policy "
    #     default-src 'self';
    #     script-src 'self' 'nonce-{{ request.csp_nonce }}' https://use.fontawesome.com https://cdn.jsdelivr.net;
    #     style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    #     font-src 'self' https://fonts.gstatic.com;
    #     img-src 'self' data:;
    #     frame-ancestors 'none';
    #     report-uri /csp-report-endpoint;
    # ";    
    add_header Referrer-Policy "referrer-when-downgrade" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;

    location / {
        proxy_pass http://localhost:8080;  # コンテナのNginxがリッスンしているポートに合わせる
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

        # CORS設定
        add_header 'Access-Control-Allow-Origin' 'https://portfolio.cobaemon.com';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept, Authorization, X-CSRFToken';

        # プロキシキャッシュの設定
        proxy_no_cache $http_x_csrf_token;
        proxy_no_cache $cookie_csrftoken;
        proxy_cache_bypass $http_x_csrf_token;
        proxy_cache_bypass $cookie_csrftoken;
        proxy_cache portfolio_cache;
        proxy_cache_valid 200 60m;
        proxy_cache_valid 404 1m;
        proxy_cache_key "$scheme$request_method$host$request_uri";
    }

    # CSPレポートエンドポイントの設定
    location /csp-report-endpoint {
        access_log /var/log/nginx/csp_report.log csp_log;
        return 204;
    }

    # カスタムエラーページの設定
    error_page 400 /errors/400.html;
    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;

    location = /errors/400.html {
        root /var/www/html;
        internal;
    }

    location = /errors/403.html {
        root /var/www/html;
        internal;
    }

    location = /errors/404.html {
        root /var/www/html;
        internal;
    }

    location = /errors/500.html {
        root /var/www/html;
        internal;
    }
}
