server {
    listen 80;
    server_name portfolio.cobaemon.com;

    access_log  /var/log/nginx/host_nginx_portfolio_http_access.log;
    error_log  /var/log/nginx/host_nginx_portfolio_http_error.log;

    # HTTPからHTTPSへのリダイレクト
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name portfolio.cobaemon.com;

    ssl_certificate /etc/letsencrypt/live/portfolio.cobaemon.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/portfolio.cobaemon.com/privkey.pem;

    access_log /var/log/nginx/host_nginx_portfolio_https_access.log;
    error_log /var/log/nginx/host_nginx_portfolio_https_error.log;

    # その他のセキュリティ関連の設定
    ssl_prefer_server_ciphers on;
    ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    # セキュリティヘッダーの追加
    add_header Content-Security-Policy "
        default-src 'self';
        script-src 'self' 'unsafe-inline' 'unsafe-eval' https://use.fontawesome.com https://cdn.jsdelivr.net https://cdn.startbootstrap.com;
        style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
        font-src 'self' https://fonts.gstatic.com;
        img-src 'self' data:;
        frame-ancestors 'none';
        report-uri /csp-report-endpoint;
    ";
    add_header Referrer-Policy "referrer";
    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";

    location / {
        proxy_pass http://localhost:8080;  # コンテナのNginxがリッスンしているポートに合わせる
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # CSPレポートエンドポイントの設定
    location /csp-report-endpoint {
        access_log /var/log/nginx/csp_report.log csp_log;
        return 204;
    }}
