[DEFAULT]
bantime  = 2592000  # バンタイムを1か月に設定（2592000秒）
findtime = 600
maxretry = 3
banaction = iptables-multiport
banaction_allports = iptables-allports
banaction = %(banaction_allports)s

[sshd]
enabled  = true
port     = ssh
logpath  = /var/log/auth.log
maxretry = 3

[nginx-http-auth]
enabled  = true
port     = http,https
filter   = nginx-http-auth
logpath  = /var/log/nginx/host_nginx_portfolio_https_error.log
maxretry = 3

[nginx-botsearch]
enabled  = true
port     = http,https
filter   = nginx-botsearch
logpath  = /var/log/nginx/host_nginx_portfolio_http_access.log
          /var/log/nginx/host_nginx_portfolio_https_access.log
maxretry = 3

[nginx-404]
enabled  = true
port     = http,https
filter   = nginx-404
logpath  = /var/log/nginx/host_nginx_portfolio_http_access.log
          /var/log/nginx/host_nginx_portfolio_https_access.log
maxretry = 3

[nginx-400]
enabled  = true
port     = http,https
filter   = nginx-400
logpath  = /var/log/nginx/host_nginx_portfolio_http_access.log
          /var/log/nginx/host_nginx_portfolio_https_access.log
maxretry = 3

[nginx-noscript]
enabled  = true
port     = http,https
filter   = nginx-noscript
logpath  = /var/log/nginx/host_nginx_portfolio_http_access.log
          /var/log/nginx/host_nginx_portfolio_https_access.log
maxretry = 3

[nginx-proxy]
enabled  = true
port     = http,https
filter   = nginx-proxy
logpath  = /var/log/nginx/host_nginx_portfolio_http_access.log
          /var/log/nginx/host_nginx_portfolio_https_access.log
maxretry = 3

[nginx-limit-req]
enabled  = true
port     = http,https
filter   = nginx-limit-req
logpath  = /var/log/nginx/host_nginx_portfolio_http_access.log
          /var/log/nginx/host_nginx_portfolio_https_access.log
maxretry = 3
