apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-omcen-org-tls
  namespace: portfolio
spec:
  secretName: portfolio-omcen-org-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: portfolio.omcen.org
  dnsNames:
  - portfolio.omcen.org
  usages:
  - digital signature
  - key encipherment
  - server auth
